### PR TITLE
Fix borderRadius Android

### PR DESCRIPTION
**Pull request by enstulen**
Fixes borderRadius on Android. Based on @bsinc's solution https://github.com/facebook/react-native/issues/3198

### CODE REVIEW

**Comment by oblador** [comment]
Thanks for your PR! Tried your code with a background color that's not white and and it would add an outline (on iOS too). Is there a way to solve this properly?

skarmavbild 2017-05-03 kl 19 58 18

**Comment by pavloko** [comment]
Hi @oblador! It seems like to apply this workaround we'd need to add background color prop to avoid the different color in the outline. I'm not sure how to evaluate the magnitude of underlying problem described in [react-native/#3198](https://github.com/facebook/react-native/issues/3198), so I can't make a definite recommendation. Do you think it makes sense to introduce this or is it better to wait for a fix in react-native?

Something like:
```
const fixCircleClipping = {
     ...
     borderColor: this.props.backgroundColorOfParentElement
};
```

**Comment by oblador** [comment]
@pavloko Right, that might be an acceptable workaround for now as it doesn't seem to happen in core any time soon. Would you mind updating the PR @enstulen?

**Comment by ddaeschler** [comment]
I've patched in the backgroundColorOfParentElement change in an up to date fork. Would you like a new PR for this issue?

**Comment by AndrewTHuang** [comment]
Has there been any progress on this one? @enstulen @pavloko @ddaeschler @oblador

**Comment by rochamorelli** [comment]
@AndrewTHuang facing this now, maybe wasn't fixed yet

**Comment by oblador** [comment]
Is this still an issue? Appears to be fixed by https://github.com/facebook/react-native/commit/30044fd531c22c4c5e8f1ede206fa7c2c3fd3aa8?

**Comment by oblador** [comment]
Closing as I believe it's fixed in RN 0.50 and no replies to the contrary

**Comment by DnEgorWeb** [comment]
Seems like this issue still exists

**Pull request closed without merging**
