### PR TITLE
Use ViewPropTypes instead of View.propTypes, as it is deprecated

### LINKED ISSUE #69: Warning: View.propTypes has been deprecated
Hey there, thanks for the lib.
I get a warning while running the debugger: `Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.` which I think is caused by [these four files](https://github.com/oblador/react-native-progress/search?utf8=%E2%9C%93&q=View.propTypes&type=).

Would it be ok if I submit a PR to fix the warning? (I saw a [PR](https://github.com/oblador/react-native-progress/pull/60) about it but was closed, wondering if there was any particular reason for that)

### PR DESCRIPTION
**Pull request by jonkessler**
Fixes #69.

### CODE REVIEW

**Comment by oblador** [comment]
Thanks! This breaks backwards compatibility though, can you address that? 😄

**Comment by jonkessler** [comment]
Sure.

**Comment by jonkessler** [comment]
How does that look? @oblador

**Comment by oblador** [comment]
Looks great, thanks!

**Pull request merged**
