### PR TITLE
Add support for gradient color in Bar progress

### PR DESCRIPTION
**Pull request by dluksza**
Adds possibility to set Bar color to gradient using
react-native-linear-gradient.

New `gradient` property was added to `Bar` property list to describe
gradient color.

### CODE REVIEW

**Comment by yarilchenko** [comment]
@oblador Hi. When this PR will be merged?

**Comment by oblador** [comment]
Sorry for the very slow review, but I'm a bit hesitant to add a dependency with a native component.

**Comment by dluksza** [comment]
I don't think that there is another way of getting gradients in NR efficiently then through native components.

**Comment by Waad-3** [comment]
how exactly can I use the gradient property in the Progress.Bar tag? without any animation.

Thank you.

**Comment by PhreakyPhillip** [comment]
Here's a way to do it in Windows 7 http://fav.me/d2rzppj


Replace uifile42 in shell32 with this code:

<element background="Gradient(argb(255, 139, 155, 181), argb(255, 152, 167, 188), argb(255, 86, 100, 113), 3)"

**Comment by HasnAr** [comment]
Hey @dluksza 
thanks for the pull request, can you provide an example of its implementation 
Best Regards

**Comment by yarilchenko** [comment]
Hello @HasnAr 
```
class SomeComponent extends Component {
    progressGradient = {
        colors: ['#d2ff19', '#09cfee'],
        start: {x: 0, y: 1},
        end: {x: 1, y: 0}
    };

    render() {
        return (
                    <Bar progress={this.calculateProgress()}
                         borderColor={`rgba(126, 122, 144, 0.5)`}
                         borderWidth={0.3}
                         useNativeDriver={true}
                         gradient={this.progressGradient}     //<-----
                         borderRadius={10}
                    >
        );
    }

}
```

**Comment by oblador** [comment]
I'm rejecting this due to added dependency and complexity of integration. Maybe it's a good package on it's own?

**Comment by dluksza** [comment]
TBH I don't want to fork this project, would prefer to have it here.

How about removing added dependency and adding an optional `prop`erty that would return progress widget? Then by default it could be a simple view, and if one would need something more advanced (like a gradient) it could be constructed within this callback.

**Comment by ManigandanRaamanathan** [comment]
@dluksza  @oblador  Any update how to get the gradient work on the progress bar?

**Comment by dluksza** [comment]
@ManigandanRaamanathan my PR should still work. Personally I do have copy of Bar component in my codebase with necessary modifications.

**Comment by mesan21ster** [comment]
@dluksza Could you please share any example to get the gradient work on the progress bar?

**Comment by seunghyun-woo** [comment]
Any updates?

**Comment by MaxJadav** [comment]
@yarilchenko  
Could you provide your fork/branch? I want to use this.  As current latest still not support this progressGradient.

**Pull request closed without merging**
