### PR TITLE
remove black fill render from progress circle on mobile apps.

### PR DESCRIPTION
**Pull request by sofianeyagoub**
there was an issue in rendering progress circle. It was rendering with a black fill, so i fixe this issue by adding a (fill) prop to let developer control the fill color of the circle.

### CODE REVIEW

**Comment by erennyuksell** [comment]
@oblador please merge this PR

**Comment by nikodunk** [comment]
Thank you @sofianeyagoub and agreed - @oblador when you get around to it please merge this PR! Renders incorrectly otherwise.

**Comment by JClackett** [comment]
Please merge!

**Comment by oblador** [comment]
Should be fixed in [5.0.1](https://github.com/oblador/react-native-progress/releases/tag/v5.0.1)

**Pull request closed without merging**
