### PR TITLE
fix #73, namespacing issue with PropTypes

### LINKED ISSUE #73: 3.4.0 Soon ? PropTypes fix is critical for RN > 0.44.0
Everything is in the title

### PR DESCRIPTION
**Pull request by mmmurf**
Fixes #73

### CODE REVIEW

**Comment by rayronvictor** [comment]
Please, merge this PR!

**Comment by oblador** [comment]
I'm not really sure what this PR is supposed to do. The real fix is in master, just have to be released which I will do in the coming days.

**Comment by mmmurf** [comment]
It's just a hack to get the PropTypes working, the cases where PropTypes
was referenced inside createClass() appeared to be pointing to
React.PropTypes

**Comment by oblador** [comment]
This library doesn't use `createClass()` AFAIK, I believe you were using v3.3.0 which doesn't have the fix.

**Comment by mmmurf** [comment]
Ahh, ok, hadn't realized there was a newer version available!

**Comment by mandriv** [comment]
@oblador any updates on this issue?

**Comment by oblador** [comment]
Fixed in [3.4.0](https://github.com/oblador/react-native-progress/releases/tag/v3.4.0).

**Pull request closed without merging**
