### PR TITLE
Art community changes

### PR DESCRIPTION
**Pull request by danielwinkler**
see https://github.com/react-native-community/art#migrating-from-the-core-react-native-module
and https://github.com/oblador/react-native-progress/issues/179

### CODE REVIEW

**Comment by dogaoz** [comment]
Can someone merge this? This fixes https://github.com/oblador/react-native-progress/issues/179
#179

**Comment by bakerac4** [comment]
Bump ^ I ran into this issue as well.

**Comment by appify-waheed** [comment]
Can someone please merge this pull request.

**Comment by club9822** [comment]
i just installed `"@react-native-community/art": "^1.0.3",` 
with
`"react": "16.8.3",
  "react-native": "0.59.10"`
 but steal [Error while updating property 'stroke' in shadow node of type: ARTShape](https://github.com/oblador/react-native-progress/issues/179)

**Comment by danielwinkler** [comment]
Is this related to the Bugfix in the release notes
https://github.com/react-native-community/art/releases/tag/v1.0.4

Can you try to update to 1.0.4?

**Comment by dogaoz** [comment]
Imagine how tired we are:

tempsnip

**Comment by andreferi3** [comment]
still got this error [Error while updating property 'stroke' in shadow node of type: ARTShape](https://github.com/oblador/react-native-progress/issues/179)

my code :
`<ProgressCircle 
     size={100}
     indeterminate={this.state.indeterminate} 
     progress={this.state.progress} 
     direction="counter-clockwise" 
     showsText={this.state.progress + '%'}
     allowFontScaling={false}
/>`

i just installed `"@react-native-community/art"`: `"^1.1.2"`, and `"react-native-progress": "^4.0.3"`,
with
"react": "16.8.3", "react-native": "0.59.10"

**Comment by vinhnglx** [comment]
@danielwinkler Thank you. It works after I installed `@react-native-community/art`.

**Comment by danielwinkler** [comment]
Great!

**Comment by Adeams1805** [comment]
Is the issue fixed ? I have every latest version and I still have the issue #179 
In the readme file it says to change the import but in which file ? All the imports of the react-native-progress module seem fine...

**Pull request merged**
