### PR TITLE
Added 'fill' option to Circle.Snail and default fill option for Circle components

### PR DESCRIPTION
**Pull request by ygzaydn**
Added 'fill' option to Circle.Snail to have control over fill property. (Default is transparent)

Also added fill:'transparent' to Circle components' default props to have transparent fill on default.

### CODE REVIEW

**Review by danleveille — APPROVED** [review]
This worked for me.

**Review by artkrv — APPROVED** [review]
Fill option is very aceptable.

**Comment by Yooooomi** [comment]
I think it is still missing the `fill` prop line 171 of Circle.js, we need to forward it to the `<Arc />` component.

**Comment by oblador** [comment]
Should be fixed in [5.0.1](https://github.com/oblador/react-native-progress/releases/tag/v5.0.1)

**Pull request closed without merging**
